packages:
  - "apps/*"
  - "packages/*"

settings:
  ignoreWorkspaceRootCheck: true
onlyBuiltDependencies:
  - "prisma"
  - "@prisma/client"
  - "@prisma/engines"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
